name: Build docker image from source and deploy to ghcr.io
on: 
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to ghcr.io
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: gabor-smith
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build docker image
      working-directory: .
      run: docker build . --file Dockerfile --tag ghcr.io/gabor-smith/nexofox-test:latest
      
    - name: Publish docker image
      run: docker push ghcr.io/gabor-smith/nexofox-test:latest
      
      
      
    
  
