name: Make docker image and deploy to ghcr
on: 
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      working-directory: .
      run: docker build . --file Dockerfile --tag ghcr.io/gabor-smith/nexofox-test:latest
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Publish docker image
      run: docker push ghcr.io/gabor-smith/nexofox-test:latest
      
      
      
    
  
